# Configuração Log4j 1.x ? problema intencional do legado
# Logs em texto livre, sem formato padronizado
# Sem correlation ID, sem structured logging

# Root logger
log4j.rootLogger=INFO, FILE, CONSOLE

# Appender de console
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattner=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

# Appender de arquivo - rotação manual, sem tamanho máximo configurado
log4j.appender.FILE=org.apache.log4j.RollingFileAppender
log4j.appender.FILE.File=logs/gateway.log
log4j.appender.FILE.MaxFileSize=10MB
log4j.appender.FILE.MaxBackupIndex=5
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattner=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

# Pacotes da aplicação
log4j.logger.com.banking.gateway=DEBUG
log4j.logger.org.springframework=WARN
log4j.logger.org.hibernate=WARN 